### ISSUE TITLE
Shopping list options

### ISSUE THREAD

**Issue by DeLaiT** [DeLaiT/Shopping-List-Android#8]
After clicking options button

![image](https://user-images.githubusercontent.com/16823955/60607236-31b78000-9dbd-11e9-85e5-fb57b7c3df25.png)

show dialog with options for selected shopping list.  

![image](https://user-images.githubusercontent.com/16823955/60607137-f9b03d00-9dbc-11e9-97e8-c1e1acb05929.png)

**Comment by victorvicari** [comment]
Have you implemented something?? Is an `Issue` or `Feature`?

**Comment by DeLaiT** [comment]
Haven't startet this yet. I can do something elese if you wants to implement this.

**Comment by victorvicari** [comment]
Take a look at your e-mail. ;)

**Comment by victorvicari** [comment]
In progress

**Comment by victorvicari** [comment]
What do you mean about "reset products"?

**Comment by DeLaiT** [comment]
By "reset products" i mean "set all products' field `done` to `false`"
